# Generated by Django 5.0.3 on 2024-03-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Computer and laptop', 'Computer and laptop'), ('smart phone', 'smart phone'), ('devices supplies', 'devices supplies')], max_length=50, null=True),
        ),
    ]
